spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sample
  profiles:
    active: dev
  config:
    import: optional:configserver:http://127.0.0.1:8071

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.attendancecheck: DEBUG